version: "3"
services:
  node:
    image: "node:latest"
    restart: always
    network_mode: host
        ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    volumes:
      - /home/ubuntu/vue/app:/opt/node/app
    container_name: couch_slave1