---
- name: build image
  become: yes
  become_user: root
  command: sudo docker build -t backend .

- name: start docker-compose
  become: yes
  became_user: root
  command: sudo docker run -p 8000:8000 backend