#Team 16: COMP90024-Assignment2
#Team Members:
#Qingmeng Xu, 969413
#Tingqian Wang, 1043988
#Zhong Liao, 1056020
#Cheng Qian, 962539
#Zongcheng Du, 1096319

 - hosts: Web-server
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true
   roles:
     - role: backend

 - hosts: CouchDB-master
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true
   roles:
     - role: couchdb-master

 - hosts: CouchDB-slave1
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true
   roles:
     - role: couchdb-slave1

 - hosts: CouchDB-slave2
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true
   roles:
     - role: couchdb-slave2

 - hosts: CouchDB-master
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true
   roles:
     - role: couchdb-set-cluster

# - hosts: Frontend
#   vars_files:
#     - host_vars/docker.yaml
#   gather_facts: true
#   roles:
#     - role: clone-repository

 - hosts: Web-server
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true
   roles:
     - role: frontend