# - hosts: localhost
#   vars_files:
#     - host_vars/nectar.yaml
#   gather_facts: true

#   roles:
    # - role: openstack-common
    # - role: openstack-images
    # - role: openstack-volume
    # - role: openstack-security-group
    # - role: openstack-instance
    # # - role: openstack-volumne-snapshots
    # - role: set-proxy
    # - role: mount-volume

#- hosts: COMP90024
#  vars_files:
#    - host_vars/docker.yaml
#  gather_facts: true
#
#  roles:
#  #   - role: docker-common
#  #   - role: docker-volume
#  #   - role: docker-installation
#    - role: docker-installation

 - hosts: Backend
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true
   roles:
#     - role: clone-repository
     - role: backend
