#Team 16: COMP90024-Assignment2
#Team Members:
#Qingmeng Xu, 969413
#Tingqian Wang, 1043988
#Zhong Liao, 1056020
#Cheng Qian, 962539
#Zongcheng Du, 1096319

 - hosts: Git-clone
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true

   role:
     - role: clone-repository