#Team 16: COMP90024-Assignment2
#Team Members:
#Qingmeng Xu, 969413
#Tingqian Wang, 1043988
#Zhong Liao, 1056020
#Cheng Qian, 962539
#Zongcheng Du, 1096319

---
 - hosts: localhost
   vars_files:
     - host_vars/nectar.yaml
   gather_facts: true

   roles:
     - role: openstack-common
     - role: openstack-images
     - role: openstack-volume
     - role: openstack-security-group
     - role: openstack-instance

 - hosts: COMP90024
   vars_files:
     - host_vars/docker.yaml
   gather_facts: true

   roles:
     - role: docker-common
     - role: docker-volume
     - role: docker-installation