---
# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: instance-vol-1-1
    vol_size: 20
  - vol_name: instance-vol-1-2
    vol_size: 20
  - vol_name: instance-vol-2-1
    vol_size: 20
  - vol_name: instance-vol-2-2
    vol_size: 20
  - vol_name: instance-vol-3-1
    vol_size: 20
  - vol_name: instance-vol-3-2
    vol_size: 20
  - vol_name: instance-vol-4-1
    vol_size: 20
  - vol_name: instance-vol-4-2
    vol_size: 20

# Security group
security_groups:
  - name: team16_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: team16_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: ['instance-vol-1-1', 'instance-vol-1-2']
  - name: instance-2
    volumes: ['instance-vol-2-1', 'instance-vol-2-2']
  - name: instance-3
    volumes: ['instance-vol-3-1', 'instance-vol-3-2']
  - name: instance-4
    volumes: ['instance-vol-4-1', 'instance-vol-4-2']
    
# Volume-mount
# volumes_mount:
#   - device: /dev/vdb
#     mountpoint: /mnt/demo
    

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: Assign2-Annette
instance_flavor: uom.mse.2c9g