---
# Show all available Openstack images
- name: Retrieve all available Openstack images
  os_image_info:
  register: image_result

- name: Get image names and Ids
  set_fact:
    # loop through all the images and retrieve their name & id and store them in the provided format
    image_facts: "{{ image_facts|default([]) + [ {'name': item.name, 'id': item.id} ] }}"
    # default is to prevent the error that cannot find the image_fact, or equivalently you could add "image_fact: []" in the file nectar.yaml
  loop: '{{ image_result.openstack_image }}'
  when: item.name is defined # onpy work when the item has a name

- name: Show images
  debug:
    msg: "Image name: {{ item.name }}; Image id: {{ item.id }}" # print out the image name and image id one by one
  loop: '{{ image_facts }} '
