---
- name: Create a directory to git repository
  become: yes
  file:
    path: /home/ubuntu/COMP90024
    state: directory
    mode: '755'

- name: Clone the repository of team 16
  become: yes
  git:
    repo: "https://https://github.com/ttcici/COMP90024-Assignment2.git"
    dest: /home/ubuntu/COMP90024
    accept_hostkey: yes
    recursive: no
    force: yes
    key_file: /home/ubuntu/.ssh/GitHub/Assign2-Annette.pem
